# Generated by Django 2.2.8 on 2020-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
