# Generated by Django 2.2.8 on 2020-04-06 19:25
# Generated by Django 2.2.8 on 2020-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = []
