# Generated by Django 2.2.8 on 2020-04-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200403_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='exclude_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='exclude_sunday',
            field=models.BooleanField(default=True),
        ),
    ]
