# Generated by Django 2.2.8 on 2020-04-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200403_1626'),
        ('users', '0003_auto_20200406_1925'),
    ]

    operations = [
    ]
