# Generated by Django 2.2.8 on 2020-04-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20200406_1927'),
        ('users', '0003_auto_20200407_1305'),
    ]

    operations = [
    ]
