# Generated by Django 2.2.8 on 2020-01-02 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('billingPeriod', models.PositiveIntegerField()),
                ('status', models.CharField(default='', max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('date', models.DateTimeField()),
                ('manualTimeSet', models.BooleanField()),
                ('hoursWorked', models.TimeField(blank=True, null=True)),
                ('isHoursWorkedAccepted', models.BooleanField(blank=True, default=False, null=True)),
                ('isCancelled', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
