# Generated by Django 2.2.8 on 2019-12-23 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('date', models.DateTimeField()),
                ('manualTimeSet', models.BooleanField()),
                ('hoursWorked', models.TimeField()),
                ('isHoursWorkedAccepted', models.BooleanField()),
                ('isCancelled', models.BooleanField()),
                ('description', models.TextField()),
                ('comment', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL)),
                ('workerSubstitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
