# Generated by Django 2.2.8 on 2020-01-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200113_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingPeriod',
            new_name='billing_period',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='hoursWorked',
            new_name='hours_worked',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='isCancelled',
            new_name='is_cancelled',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='isHoursWorkedAccepted',
            new_name='is_hours_worked_accepted',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='manualTimeSet',
            new_name='manual_time_set',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='workerSubstitution',
            new_name='worker_substitution',
        ),
    ]
