# Generated by Django 2.2.8 on 2019-12-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=40)),
                ('houseNo', models.PositiveIntegerField()),
                ('flatNo', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
            ],
        ),
    ]
