# Generated by Django 2.2.8 on 2020-01-02 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=40)),
                ('houseNo', models.PositiveIntegerField()),
                ('flatNo', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.AddressOwner')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
