# Generated by Django 2.2.8 on 2020-01-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='00-001', max_length=12),
        ),
    ]
