# Generated by Django 2.2.8 on 2020-01-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_no',
            field=models.CharField(max_length=10),
        ),
    ]
