# Generated by Django 2.2.8 on 2019-12-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20191221_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flatNo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
