# Generated by Django 2.2.8 on 2020-01-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_address_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='flatNo',
            new_name='flat_no',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='houseNo',
            new_name='house_no',
        ),
    ]
