# Generated by Django 2.2.8 on 2020-01-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
