# Generated by Django 2.2.8 on 2020-01-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200113_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contactName',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='contactPhone',
            new_name='contact_phone',
        ),
    ]
