# Generated by Django 2.2.8 on 2020-01-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200113_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
