# Generated by Django 2.2.8 on 2019-12-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebaseId',
            field=models.CharField(editable=False, max_length=191, unique=True),
        ),
    ]
