# Generated by Django 2.2.8 on 2020-01-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firebaseId',
        ),
    ]
