# Generated by Django 2.2.8 on 2020-01-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_firebaseid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='dateEnd',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='absence',
            old_name='dateStart',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
