# Generated by Django 2.2.8 on 2019-12-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191222_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebaseId',
            field=models.CharField(max_length=191),
        ),
    ]
