# Generated by Django 2.2.8 on 2020-01-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200115_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Coordinator', 'Coordinator'), ('Worker', 'Worker')], max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
