# Generated by Django 2.2.8 on 2020-01-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200113_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cognito_id',
            field=models.CharField(default=1, max_length=191),
            preserve_default=False,
        ),
    ]
