# Generated by Django 2.2.8 on 2019-12-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191220_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='state',
            field=models.CharField(help_text='pending/confirmed/rejected', max_length=30),
        ),
    ]
