# Generated by Django 2.2.8 on 2019-12-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191221_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='state',
            field=models.CharField(choices=[('Pending', 'pending'), ('Confirmed', 'confirmed'), ('Rejected', 'rejected')], default='Pending', max_length=9),
        ),
    ]
